### ISSUE TITLE
Duration of tokens

### ISSUE THREAD

**Issue by cnelson** [electric-it/cagophilist#32]
Today cago does not provide the option to change the  `DurationSeconds` option passed to `AssumeRoleWithSAMLInput` which causes all tokens issued to be valid for the default time (3600 seconds) even if the role being assumed supports longer token lifetimes.

It would be helpful if cago could request longer duration tokens, but since we can't know the duration allowed for a given role before we've authenticated I think it'd have to be up to the user to provide (perhaps as a command line argument to `cagor` something like `cagor --duration 43200`

What do you think?  Would you merge a PR which would allow the user to specify the duration of the token?

**Comment by cnelson** [comment]
@berniedurfee-ge @berniedurfee bump. Some feedback would be great before I start writing code :)

**Comment by berniedurfee-ge** [comment]
Hi @cnelson sorry for delay! Yes, this would be a great feature. You can add the flag to the `refresh-profiles` Cobra command and then pass that through conditionally in the `getTempCredentials()` function. Thanks!

**Comment by berniedurfee-ge** [comment]
This is working as of Cago v2.5.0... which has moved to [GitLab](https://gitlab.com/electric-it/cago)
